import { Button, VerticalBox, CheckBox, LineEdit, StandardTableView, Switch, Slider, SpinBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    out property <string> user_name: uname.text;
    out property <string> url: url.text;
    in-out property <string> passphrase;
    out property <string> notes: notes.text;
    out property <int> passlength: l.value;
    callback request-increase-value();
    callback request-decrease-value();
    callback exit();
    callback clear_form();
    callback new_pass_clicked();
    callback update_db_clicked();

    property <bool> active: true;
    property <InputType> is_pass: password;
    property <InputType> is_not_pass: text;
    
    states [
        active when active: {
            pass_phrase.input-type: password;
        }
        inactive when !active: {
            pass_phrase.input-type: text;
        }
    ]

    VerticalBox {
        
        GridLayout {
            padding: 25px;
            spacing: 5px;
            Row {
                Button {
                    text: "New Password";
                    clicked => {
                        root.new_pass_clicked();
                    }
                }
                Button {
                    text: "Copy Passphrase";
                    clicked => {
                        pass_phrase.select-all();
                        pass_phrase.copy();
                        pass_phrase.clear-selection();
                        
                    }
                    height: 30px;
                }
                Button {
                    text: "Copy Username";
                    clicked => {
                        uname.select-all();
                        uname.copy();
                        uname.clear-selection();
                        
                    }
                    height: 30px;
                }
                Button {
                    text: "Exit";
                    clicked => {
                        root.exit();
                    }
                    height: 30px;
                }
            }
            
            Row {
                Text {
                    text: "User Name";
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }
                uname := LineEdit {
                    col: 1;
                    colspan: 3;
                    max-height: 25px;
                    padding-top: 25px;
                }
            }
            Row{
                Text {
                    text: "URL";
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }
                url := LineEdit {
                    col: 1;
                    colspan: 3;
                    max-height: 25px;
                    padding-top: 25px;
                }
            }
            Row{
                Text {
                    text: "Passphrase";
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }
                pass_phrase := LineEdit {
                    text: root.passphrase;
                    col: 1;
                    colspan: 3;
                    max-height: 25px;
                    padding-top: 25px;
                    input-type: password;
                }
            }
            Row{
                Text {
                    text: "Notes";
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }
                notes := LineEdit {
                    col: 1;
                    colspan: 3;
                    max-height: 25px;
                    padding-top: 25px;
                }
            }
            Row {
                Button {
                    text: "Clear Form";
                    col: 1;
                    clicked => {
                        uname.text = "";
                        url.text = "";
                        notes.text = "";
                        root.new_pass_clicked();
                    }
                    height: 30px;
                }
                Button {
                    text: "Edit";
                    height: 30px;
                    col: 2;
                    clicked => {
                        root.update_db_clicked();
                    }
                }
                Button {
                    text: "Add";
                    height: 30px;
                    col: 3;
                    clicked => {
                        root.update_db_clicked();
                    }
                }
                
            }
            Row {
                StandardTableView {
                    colspan: 4;
                 }
            }
            sw := Switch {
                text: "Switch";
                checked: true;
                toggled => {
                    active = !active;
                }
            }
            
            l := SpinBox {
                minimum: 8;
                maximum: 100;
                value: 15;
                changed value => {
                    passlength = self.value;
                }
            }

        }
        
    }
}
